### ISSUE TITLE
Maximum call stack size exceeded on pickr.setColor(null)

### ISSUE THREAD

**Issue by AlbertRAR** [Simonwep/pickr#105]
1. navigate to https://jsfiddle.net/albert_rar87/c164e39n/12/
2. Open the color picker then click Save button https://nimb.ws/9SQ6gb
3. Open browser console to see Maximum call stack size exceeded error https://nimb.ws/yeSU2P

**Comment by Simonwep** [comment]
`setColor` triggers the save event so yeah, you get an endless loop. You can pass `true` as second argument to prevent the triggering of any event. Seems like I forgot it in the case of clearColor. Fixed in 3eeda6e62f1d6f4cecaac5fc97cad972c9ed6c07

Your updated fiddle with `true` as second arg added: https://jsfiddle.net/vx1hwmr7/ :)

**Comment by AlbertRAR** [comment]
Thanks for clarifying.
