### ISSUE TITLE
Shorthand hex code is not converted correct

### ISSUE THREAD

**Issue by bjarnef** [Simonwep/pickr#108]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
It seems there is an issue when using shorthand hex code, e.g. `#F00` and saving the value using `toHEXA()` where the value becomes `#F00F00`. Maybe it is also an issue with the other functions `toCMYK()`, `toHSLA()`, `toHSVA()`, `toRGBA`.

It doesn't seem to be an issue with shorthand hex codes like `#000` or `#333`.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/71rv3po8/).
Check the linked JSFiddle and see the console log when clicking save button.

#### What is the expected behavior?
When using the shorthand code I would expect e.g. that `#F00` is converted to `#FF0000`.
https://www.colorhexa.com/ff0000

Off topic: Should `defaultRepresentation` the value `HEXA` as the color picker shows? It could accept both `HEXA` and the existing value `HEX` (or is it a typo in the docs?) https://github.com/Simonwep/pickr#options
The `interaction` however has a `hex` (not hexa) property.

#### Your environment:
```
Version (see Pickr.version): 1.0.0
Used bundle (es5 or normal one): normal
Used theme (default is classic): classic
Browser-version: Google Chrome Version 75.0.3770.90
Operating-system: Windows 10  
```

![chrome_2019-06-19_00-15-25](https://user-images.githubusercontent.com/2919859/59723863-1dee1480-9228-11e9-8dec-567138b5901c.png)

**Comment by Simonwep** [comment]
Woah thanks, fixed in a5234f48b10e0441a4e31022daea57fbe15e466d... damn - the affected code is like ~30 versions old :suspect: 

Regarding `defaultRepresentation`, yes this is by purpose. There where some backwards compatibility issues where an `a` if missing get's automatically _autocompleted_... see #83 - there was another issue but I cannot find it anymore where the change from `HEX` to `HEXA` (since it was indeed hex with alpha) caused issues :/

If the alpha value is `FF` it won't be displayed since most software got full opacity as default (I hope)
