### ISSUE TITLE
Clearing, Cancelling, and Clicking Questions

### ISSUE THREAD

**Issue by Jetroid** [Simonwep/pickr#118]
Hi @Simonwep,

I have questions about pickr, both so I can clarify the readme further, fix some potential bugs, and perhaps add a few features:

**What is a use case of the 'clear' button?**

I had been using pickr with a custom button in my experiments (ie `useAsButton: true`), and assumed that it's functionality was just a form of 'cancel' that also closed the window. That was the functionality I believed I was experiencing and I updated the README to say as such, too! 

But now I'm confused about what 'clear' is for, because I found that if I use the default button, it sets the color to rgb(0,0,0,0.15). This seems to come completely out of left field for me, as it's not really clearing the color - a slightly opaque black is still a color. A clear color is opacity 0. I also saw that the save event fires null! But the _color and _lastColor state variables are also not changed. So I'm confused about what the 'clear' button is supposed to be 'for'. 

If the intention is that it clears the color to transparent, then we should set to rgb(0,0,0,0) and emit the appropriate HSVaColor. Understandably, this breaks the default button (as it becomes transparent (albiet with an X), so perhaps it would be wise to add a chequerboard transparency indicator there instead. (This thing: http://clipart-library.com/images/pi7rbyXxT.jpg )

Regardless of the intention, I think that the _color and _lastColor state variables not updating to represent the move to rgb(0,0,0,0.15) must surely be a bug, as the modal (when re-opened) is not showing the same colours as the button.

**Should the cancel button close the application?**

Personally, it seems counter-intuitive to me (as a user) to leave open the window after pressing cancel.

Additionally, there isn't a callback for the cancel (and similarly, clear) events for a developer to add this functionality in manually. So I propose we add ways for the developer to make this possible if they want it. 

Possible solutions:
add `closeOnCancel` and `closeOnClear` booleans (which I think should default to `true`)
add `cancel` and `clear` events (Perhaps we should do this anyway, just to make the tool more hackable!)

**Should we add more options for clicking outside of the modal?**

Currently, when we click outside of the modal, it is equivalent to `pickr.hide()`. 

I propose that it could be useful to add the option to change this functionality from `hide` to `cancel` (the same as if I had clicked the `cancel` button -  reset `_color` to `_lastColor` and everything that comes with it.
Or, again, perhaps another event listener (though I personally can't see many use cases for it). 

**What are your thoughts, @Simonwep?** I raise these issues because of a few incongruences between the actions I was expecting from pickr, and the actions that actually happened.

**Comment by Simonwep** [comment]
Hey @Jetroid  :D

#### About the clear button
Initially, pickr only hat the ability to replace `el` and show a button where the user could select a color. The `clear` button was made as a response to #5 since the user could only select _fully transparent_. But there may be edge-case where the user wants to select "no" color (please don't ask me, after one year I have no clue for what and why, it's just there...).

And because I've (presumably) only got the button itself as target back then - I've decided to make it transparent and add a X as overlay to indicate that there's no color selected. Pickr fires the `save` event with `null` as color - `_lastColor` and `_color` should not change since there is no color. But `pickr.getColor()` returns the _last_ color which is _indeed_ a **bug**.


#### About cancel
Well, other users seem to expect to close it, see [this comment](https://github.com/Simonwep/pickr/issues/106#issuecomment-506741346_) in #106. Cancel although also fires a save event with the current color, but maybe - yeah there could be an additional cancel even.  

Well, I think clicking outside of it - and getting the color _resetted_ would really confuse me. Why did the color jump back to the previous one, I haven't done anything except clicking outside of it ^^

#### Conclusion
1. Clicking `clear` should set `_color` (and `_lastColor`?!) to `null` since `getColor` returns the old, now invalid value. I should **not** be the same as fully transparent e.g. `rgba(r, g b, 0)`
2. In response to 1. - cancelling should then work fine as it will (as expected) set the color back to `null` / `none`. It may not be the same as `null` but this would be redundant with additional events.
3. There could / should be a separate event for `cancel` and `clear`, **but** what about the existing mechanic that clear fires save with `null`, should wee keep that? 

If there are seperate events for cancel and clear. There's no need for an extra `closeOnCancel` or `closeOnClear` option. I want to keep it as small as possible :)

And thank you very very much about your contributions! Your breathtaking :) If you want I can invite you as contributor and we can plan these things on the project board (Which is empty lol, since I'm so far the only maintainer)

**Comment by Jetroid** [comment]
Thanks for the prompt response, @Simonwep.

1. Are you proposing that getColor() should be changed to return _lastColor, and that the new getSelectedColor() returns _color? And that clicking `clear` would cause both of those functions (or perhaps just getColor() ?) to return `null`? 

Setting _color and _lastColor both to `null` probably causes a lot of problems for us (as we expect them to be set in our internal functions (eg: https://github.com/Simonwep/pickr/blob/master/src/js/pickr.js#L236), so it might be simpler to add a new internal variable like _isClear which is read by the getColor() and lastColor() functions to know whether to conditionally return null or not.   

2. Not sure what you meant by point 2.). Sorry!

3. I'd suggest keeping the save event firing with null for backwards compatibility. I agree that if we had to pick just one approach, I prefer events for `cancel` and `clear` as it is more hackable than `closeOnCancel` and `closeOnClear`. 

However, I disagree that there isn't value to `closeOnCancel` and `closeOnClear`, as it helps users reduce bloat in their own code and isn't a huge size increase. If we're rejecting something like `closeOnCancel`, then I question the logic of implementing a `closeOnScroll`; `closeOnCancel` and `closeOnClear` each take just as much code inside pickr as `closeOnScroll` did, and `closeOnScroll` could be implemented by the user manually, just as `closeOnCancel` and `closeOnClear` could.

4. "Well, other users seem to expect to close it, see this comment in #106. Cancel although also fires a save event with the current color, but maybe - yeah there could be an additional cancel even."

Both @bjarnef and @MRVDH wanted/expected it to close, and I do too. The functionality I'm currently experiencing is that it stays open when clicking cancel. I propose switching the functionality to close the window by default rather than leaving it open.

**Comment by Simonwep** [comment]
1. Yes, since no color would be the selected, and current one :)
2. I you press `clear` - and then `cancel`. Save get's fired with `_color` which is not null - even if the user clearly cleared the color before.
3. Absolutely agree to events! Wouldn't take more than 20/50 bytes.

`closeOnScroll` was made since it would be way to complicated to react to nested scrolling. So if the dev _really_ want's to put pickr into such a container - he can set this option to true without damaging the user experience.

If we agree to implement `cancel` and `clear` events, maybe we could drop `closeOnScroll` on the next minor version and provide a hack in the README  or somewhere else to close it if the user scrolls, would totally prefer that. I really don't like static props or options like that.

Oh I thought you mean you would prefer to _not_ close it haha - yeah. I'm fine with closing it, you're right.

**Comment by Simonwep** [comment]
I've added a ton of events, I think it's easier (especially It would require no change in the core code) if the `cancel` event is used to close pickr:
```js
pickr.on('cancel', () => pickr.close())
```

**Comment by makepanic** [comment]
> 
> ```js
> pickr.on('cancel', () => pickr.close())
> ```

I think it should be `pickr.hide()` as there's no close method.

**Comment by Simonwep** [comment]
Whops yeah, I mean
```js
pickr.on('cancel', () => pickr.close())
```

Sorry, my bad.

**Comment by NateSeymour** [comment]
This issue appears to be resolved. If this is not the case, please let me know.

Have a great day! :)
