### ISSUE TITLE
Not able to add color picker on multiple element with class

### ISSUE THREAD

**Issue by harishkpc** [Simonwep/pickr#127]
I am not able to add color picker on multiple element with class

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md) when you create a new one. This will help me to resolve it as fast as possible. Here's a demo with two pickrs on the same page: https://simonwep.github.io/pickr/dist/themes/classic.min.css

**Comment by harishkpc** [comment]
added color picker on two filelds with same class like follwoing screenshot
http://prntscr.com/oivfal
But its working on one button

**Comment by Simonwep** [comment]
I can't open the page, it's still loading. Why would you want to assign a single pickr instance to multiple elements? That makes no sense, one pickr instance - one element. Otherwise how would you handle events? And what should `getColor` return? Two colors?

As I showed in the fiddle use two different classes or pass the HTMLElement directly to `el` :)

**Comment by Simonwep** [comment]
And duplicate of #57 and #30
