### ISSUE TITLE
Empty or clear color and issues with setColor

### ISSUE THREAD

**Issue by mafar** [Simonwep/pickr#140]
Hi,
I am running into situation in app where i am using ```pickr``` to apply colors to different curves.

problem is ```pickr``` should have 

1. ```pickr.clear()``` function so that color`s value is empty string
1. ```clear()``` button click should apply value empty string , currently it is applying #0000 which is again a black color and there is no way of telling if it was cleared
1. there is no way of telling from ```}).on('hide', instance => {``` that hide was triggered from buttonclick, programatic call , clear button click etc

**Comment by mafar** [comment]
there is no way of defining no color or empty color as initial state , hence it can not be used in forms where there is no color initially and user has to select one.
it is forcing black color as clear color which is wrong

**Comment by mafar** [comment]
```pickr.setColor('gggggggggggggggggg, false)```  returns ```true``` which is wrong

**Comment by mafar** [comment]
See this plugin.. supports initial clear state
![image](https://user-images.githubusercontent.com/4101480/63418051-4b397900-c3b7-11e9-95d7-1403930e7cea.png)

**Comment by mafar** [comment]
See https://codepen.io/mafar/pen/pozNeeB?editors=0010

This plugin has some serious issues.
Its really hard to use it in form 
If i am giving 
```<input class="pickr" type="button" value="s" name="color">``` as el 
then i expect name and value attributes to be carried over to generated template

And instead of button, it should use input as main style

Clear() is not working. always reverts back to black which is a blocker

**Comment by Simonwep** [comment]
_1. Well, you're free to use spectrum which seemingly doesn't have serious issues._
2. Initial state such as clear can be applied in the `init` event.
3. I've fixed the bug with `ggg...` in e9b6b620a272a503a685e89bc79f2c89c4084447
4. I won't add pickr.clear, use `pickr.setColor(null)` to clear it, see [methods](https://github.com/Simonwep/pickr#methods)
5. Differenting where `hide` was called was never requested, you can do a feature request with a reason why this should be added.
6. Same thing with no-color, makes sense so I'll probably implement it anyway - but feel free to make a feature request for it.
7. There is no `Clear()` function, what do you mean? Pickr is not meant to be used in forms like that, and "polyfilling" `input[type=color]` is already under consideration, see #11

**Comment by mafar** [comment]
Ok i guess I will make separate issue for every thing but
```pickr.setColor(null)``` i acutally tested it yesterday and was not workinf for me because i was using it like ```pickr.setColor('')```

Because in JS
 '' and null both are considered netagive boolean if ( '') { // will be same as false or null}
Consider using this lib in form where user has inputfield color and it can hvae hex color string as value if it has color selected or it can be empty string means no color.Because Forms are working with be , Formfield color in BE has type string always either empty or HEx or RGB value

**Can u consider** 

1. empty string as null ? in ```pickr.setColor()```
2. Invalid string should be treated as .setColor(null)  clear , instead of forcing black color if not silent

This is important in usecases where a field can have a color defined or no color

**Comment by mafar** [comment]
also see here https://codepen.io/mafar/pen/pozNeeB?editors=0010

I use ```{  default:  null }``` as option but when on init I ask for ``` .getColor()``` it says ```#000000```

**Comment by Simonwep** [comment]
Well, it's mentioned to use `null`, not a false-ish value. I know. I did this on purpose since theres already enough chaos in js with these kind of stuff, and explicitly saying to use null makes things more clear and strict.

I'm confused by your second paragraph, but the thing with input types is already covered in #11, I won't repeat which I already wrote there.

To your concerns
1. No, I'll leave this explicit, may be a braking change otherwise. Use a or-operator like `setColor(color || null)`.
2. It's related to 1., but i'll investigate a better solution for it, it's a known-issue for me as your last comment where `getColor` returns black.

**Comment by mafar** [comment]
**For Point 1**  
Please see this https://github.com/Simonwep/pickr/compare/master...mafar:patch-1  for Point 1 above. It is not code breaking and will support undefined,null empty string and undefined

**For Point 2**  
Idea could be if clear is called , it can set an internal variable like ```this._noClor = true``` and then 
on save  ```this._noClor = false```

and then
```
    getColor() {
        if(this._noColor){
            return '';
        }else{
            return this._color;
        }        
    }
```

Not sure if this is a smart idea though but not a bad one either
becuase then users will need to 
```
if ( instace.getColor() ){
 console.log(instace.getColor().toHEXA().toString();); // chain
}else{
  console.log('clear state');
}
```

**Comment by Simonwep** [comment]
@mafar This is a brilliant example of how this could break someones code, what if in some application a empty string is passed, or undefined as keyword? Yeah - the color will be set to `none`. A breaking change is something which could cause other applications to misbehave - yes you would implement this in that way but but no. I won't change that as I already said since I want to have at least a partially type-save code base - even if it's just in that way.

To the second one, why would you return an empty string? That makes no sense and people would think that it's an bug. Null would be way more straight and explicit. And I won't add another instance variable just for this simple issue, I'll probably set `_color` to `null` and refactor a little bit.

**Comment by Simonwep** [comment]
And why should `default: null` work? Which color should be chosen if the user opens pickr? Use a base-color as default and use `setColor(null)` in the init event. Otherwise the _actual_ color which is selected by the UI isn't defined.

I've fixed the problem where `getColor` returns black in 84d8b0a2b6e1d83dde58d526f9e570c8509291c0

**Comment by Simonwep** [comment]
Change the API slightly, otherwise it'd be strange. I've added a `getSelectedColor` function which returns the currently selected color, e.g. `null` if no color is chosen.

**Comment by NateSeymour** [comment]
> See https://codepen.io/mafar/pen/pozNeeB?editors=0010
> 
> This plugin has some serious issues.
> Its really hard to use it in form
> If i am giving
> `<input class="pickr" type="button" value="s" name="color">` as el
> then i expect name and value attributes to be carried over to generated template
> 
> And instead of button, it should use input as main style
> 
> Clear() is not working. always reverts back to black which is a blocker

@mafar, Not to stick my head where I don't belong, but you need to seriously reconsider how you interact with maintainers of open source projects: you are not Linus Torvalds.

Please, in the future, for my sanity and the sanity of all other open source developers:

1. Proofread your comments for grammar mistakes. When you don't care enough to capitalizing the letter "I" or to write out "you," very few people are going to put in the effort to help you solve your problems.

2. When creating issues on open source projects, please read the READMEs and documentation first. Like Simon has kindly pointed out, most of the issues that you have pointed out have actually been documented behavior.

3. Please do not argue with the creator of a project about what is code-breaking or not if you have not been involved in the active development of said project.

4. In 2019, using `var` in any Javascript project is unacceptable. Please do not make code suggestions involving it, and when working on any ES6+ project, make sure you first inform yourself of the new coding conventions first. A lot has changed since the old JS days. 

5. Please do not argue with the creator/maintainer of an open source project about what the project should be or what its intended use case is.

6. Please do not send the creator/maintainer of an open source project links to other similar projects and state that they are better and that their features should be copied. If you prefer another open source project, because it fits your use-case better or other features that you need: use it instead. The beauty of having such a widely diverse open source community is that we developers have the options to use any number of projects that offer any number of different pros/cons. There are hundreds of open source color pickers to choose from online. What sense would it make if they were all exactly the same?

7. Always be kind and be polite. Nobody here works for you. In fact, nobody here is working for anybody or making any money from this project at all. Respect that this open source project, like many others, is being developed by people who already work a full time job elsewhere, and develop open source projects in their free time. They then make them available to everyone on the internet (including you), free of charge, out of the kindness of their hearts. Being rude to them on the internet serves only to gain you nothing, and to rob them of their time they spend doing what they love. 

Don't be discouraged from helping! As an open source community we absolutely love chatting with other developers and working collaboratively on projects. Just please be sure to follow these (loosely defined) rules so that we can all have a good time.

Thank you and have a wonderful day :)
