### ISSUE TITLE
Inline mode broken again

### ISSUE THREAD

**Issue by bjarnef** [Simonwep/pickr#148]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
I noticed recently in version 1.3.0 the inline mode no longer seems to work. I upgraded to latest version 1.4.1, but it seems inline mode is still not working as expected. It seems to reserve whitespace for the inline color picker, but it show the same overlay as when `inline: false`.

#### What is the expected behavior?
Using `inline: true` should show the picker inline.

#### Your environment:
```
Version (see Pickr.version): 1.4.1
Used bundle (es5 or normal one): Normal
Used theme (default is classic):  Classic
Browser-version:  Google Chrome Version 76.0.3809.132
Operating-system: Windows 10
```

**Comment by Simonwep** [comment]
What do you expect `inline` should do? Yes, it reserves white-space - this is essentially what inline does, it's _inlined_.

**Comment by bjarnef** [comment]
Previously it showed the color picker inline, when `inline:true`. I would expect the `inline:true` was showing the picker as inline in the reserved whitespace area and not a color picker overlay.

**Comment by NateSeymour** [comment]
Sorry for the confusion, but this is indeed intended behavior and we have forgotten to update the docs when we made the change in 854a33a to close issue #136.

The docs have been updated to reflect this change. In order to use `inline` mode as you intend, please set both `inline` to true and `showAlways` to true as in this JSFiddle: https://jsfiddle.net/Simonwep/tu0vkz53/

Let me know if you have any other questions, and have a great day!
