### ISSUE TITLE
Replace/Disabling of the "button"

### ISSUE THREAD

**Issue by fxOne** [Simonwep/pickr#22]
#### Do you want to request a **feature** or report a **bug**? 
I want a new feature.

#### What is the current behavior?
Currently it is not possible to replace the "pcr-button" with an icon or something else. The only option is to overwrite the css class and hide the button by setting the opacity to 0. Hiding the button does not work as it breaks the positioning of the component.

#### What is the expected behavior?
It would be nice if I could replace the button with an icon or disable it in the config like all other buttons.

#### Your environment:
```
Pickr-version: 0.1.7  
```

**Comment by Simonwep** [comment]
Greate idea! I will try to add it in a few days!
Would be something like attaching the pickr-ui to any element which you like. This element would then represent the 'button'.

**Comment by Simonwep** [comment]
So, now since d2408243047ad79d2d210ed06432bef76a441500 you can use a custom element as button.
To enable this simply add `useAsButton: true` to your pickr-options. Your `el` Element will be used as button (and also get the `clear` / `disabled` classes so you can apply some fancy styles 😄). Be aware, this would cause that the option `appendToBody` is true, so it won't affect your custom button!

And regarding to disabling I've done this in d2408243047ad79d2d210ed06432bef76a441500. You can use `pickr.disable()` to disable it and `pickr.enable()` to enable it. Moreover you can use the option `disabled: true | false` if the pickr should be disabled from the beginning.

It's currently not finish or fully tested and therefore not mentioned in the README, maybe I drop a new version at the end of this week...

**Comment by Simonwep** [comment]
I think the feature request has been solved. I'll close this issue.
