### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by ziadevcom** [Simonwep/pickr#220]
#### Your question
Can we set the default value of Pickr o Gradient? If yes, can you please guide. Thanks

#### Your environment:
```
Version (see Pickr.version):
Used bundle (es5 or normal one):
Used theme (default is classic): 
Browser-version:  
Operating-system:  
```

**Comment by ziadevcom** [comment]
I figured it out with custom CSS but is there any possibility to achieve this through the picker object? That would be better, right?

**Comment by ziadevcom** [comment]
Or later on, set the preview/default color to the selected color. Is this possible?

**Comment by Simonwep** [comment]
Sorry, won't do that. Pickr itself is already difficult enough to maintain due to its age and setup. Pickr with gradients was a project a while ago though, you might want to checkout [gpickr](https://github.com/Simonwep/gpickr).

I'm considering working on a v2 with plugin support were that could be possible.
