### ISSUE TITLE
Nanopop `update` issue when using with Pickr and large screen sizes

### ISSUE THREAD

**Issue by alexdiliberto** [Simonwep/pickr#231]
First off, just wanted to say I'm really enjoying your Pickr library. 

I do have an issue I'm running into on my app that seems to be Nanopop/positioning related. I wasn't sure which library to raise the issue (Pickr or Nanopop) but I'll try here. I have a minimal reproduction on this Codepen:

https://codepen.io/alexdiliberto/pen/vYLrxyq

You can see the issue if you start resizing your screen larger and larger then it seems to begin throwing off the positioning until it finally fails.

1680px screen width **(expected behavior)**

<img width="536" alt="Screen Shot 2020-07-10 at 11 51 24 AM" src="https://user-images.githubusercontent.com/666459/87173570-f9862f80-c2a3-11ea-80a7-20c32bf7c80c.png">

2300px screen width

<img width="544" alt="Screen Shot 2020-07-10 at 11 51 39 AM" src="https://user-images.githubusercontent.com/666459/87173644-11f64a00-c2a4-11ea-9222-2daefbc427b8.png">

2450px screen width

<img width="578" alt="Screen Shot 2020-07-10 at 11 54 45 AM" src="https://user-images.githubusercontent.com/666459/87173714-2cc8be80-c2a4-11ea-8f73-f4feed7038de.png">

2600px screen width

<img width="1676" alt="Screen Shot 2020-07-10 at 11 51 45 AM" src="https://user-images.githubusercontent.com/666459/87173780-410cbb80-c2a4-11ea-802b-d9140b866afc.png">

eventually on large screens it seems to fail [this conditional](https://github.com/Simonwep/pickr/blob/1.7.1/src/js/pickr.js#L516-L521) and just places the pickr app in the center of the screen

Any assistance would be greatly appreciated, none of the public API's for Pickr helped in this case...I manually set `this._recalc` (https://github.com/Simonwep/pickr/blob/1.7.1/src/js/pickr.js#L513) to `false` and that seemed to help by just now allowing the final fail case where it places the pickr app in the center of the screen.

**Comment by Simonwep** [comment]
Okay this is a misconfiguration in pickr. The solution was to [update](https://github.com/Simonwep/pickr/commit/b9efcb72687785a9a6059b11d6860d55fa225cd0#diff-089a8fbaf505793bcbfa9dd2b81e7455R513) the clipping-container each time pickr gets repositioned. I forgot that this value is static and has to be updated each time e.g. it only recognized the screen-size on first page-load leading to miscalculations.

Fixed in b9efcb72687785a9a6059b11d6860d55fa225cd0, if you want you can test it using the latest builds from master and if everything works as expected I'll release a patch version ASAP.

**Comment by alexdiliberto** [comment]
@Simonwep Wow thank you for the quick response. Just checked using master branch in my application and this seems to be working perfectly now. 💯 🥇

**Comment by Simonwep** [comment]
Great! Patch available in [1.7.2](https://github.com/Simonwep/pickr/releases/tag/1.7.2) :)
