### ISSUE TITLE
How to Override input field

### ISSUE THREAD

**Issue by oiver555** [Simonwep/pickr#265]
I would like to know how can I override the input field. I want to use the input as a field for users to give their color a name. I have been trying to figure out how to override, but whenever I change the field it affects the palette. OR is this something that I should not be doing? I figured instead of making one why not try and re-purpose the one that is made with Pickr.js

#### Your environment: Not sure what to put here 
```
Version (see Pickr.1.8.0):
Used bundle (es5):
Used theme (default is classic): 
Browser-version:  Google Chrome Version 88.0.4324.96 (Official Build) (64-bit)
Operating-system:  Windows
```

**Comment by Simonwep** [comment]
This is not possible and won't be. The input's solely purpose is to parse whatever the user is putting into it as a color and displaying it. If you want your users to give it a name, just add your own input field right next to / below pickr so that, after the user chose a color, a name can be given to it (and saved to a database or whatever). Using the input field to _name_ a color would be confusing and is not indented.

**Comment by oiver555** [comment]
Ok I understand, Thanks for the quick response
