### ISSUE TITLE
HEX Code to HVSA vice versa is not accurate

### ISSUE THREAD

**Issue by hcomnetworkers** [Simonwep/pickr#27]
#### Do you want to request a **feature** or report a **bug**? 
bug

#### What is the current behavior?
Setting specific HEX codes for colors are changed in the preview for colors and for the `onSave` method.

#### If the current behavior is a bug, please provide the steps to reproduce.
Open https://jsfiddle.net/fs5re70h/

- Initial default value is `#D6A9DB` 
- Opening the Pickr does display `#D5A9DB`
- Clicking into the input field for manually setting a HEX code does change it to `#D4A9DB`

- Use the button to set `#D5A6DB`
- Opening the pickr widget will preview the HEX color code `#D4A9DB`.

#### What is the expected behavior?
The HEX color code should not change.

#### Your environment:
```
Pickr-version: 0.1.9, reproduced on 0.2.0 with the jsfiddle
Browser-version:  Chrome 68
```

**Comment by Simonwep** [comment]
Yeah, It's a known bug... not only with hex as far as I know. I'm working on it!

**Comment by Simonwep** [comment]
Well, it's actually not really an bug. Just a rounding-error which is caused by `Math.round()`. I was abel to fixed this by using `toFixed(1)`. Not every color can be represent by `hsv` 'cause s & v  are from `0 - 100` and not from 0 to 255 so informations got lost.

**Comment by Simonwep** [comment]
Yes, now I use (internal) floats instead of rounding it and some bugs has been solved. And yes, but I need to use any _base_ color :/.

Unfortunatly it's quite essential (and logical) to use `hsv` because the visual representation, is the representaion of `hsv`. `hsl` is exactly the same regarding to the number range `0-100`, used it before but was harder to visually represent. I will re-code the core of pickr and try (better) isolate the input from the output.

**Comment by hcomnetworkers** [comment]
Thanks for the quick responses and work. Really appreciate it.

**Comment by Simonwep** [comment]
Finally, damn, should have payed earlier to this attention :)
JSFiddle: https://jsfiddle.net/7m6ca2vp/13/

**Comment by hcomnetworkers** [comment]
Thats amazing, thanks for your work :)
