### ISSUE TITLE
Default Color issue

### ISSUE THREAD

**Issue by sudheerm589** [Simonwep/pickr#59]
default color is not applying to the pickr

**Comment by Simonwep** [comment]
Could you please provide information how to reproduce it? Maybe a [JSFiddle](https://jsfiddle.net/).

**Comment by SkaveRat** [comment]
I can confirm this issue, but can't seem to replicate it in JSFiddle

What happens, however, seems to be that `.pcr-palette` and `.pcr-picker` don't get their styles set untill a user clicks on the palette. Before that the palette shows a checker pattern.

This also only started happening when updating to 0.3.4 (before I had 0.3.2)

**Comment by Simonwep** [comment]
Which browser (/ version) do you guys use? Seems like a strange bug

**Comment by sudheerm589** [comment]
We used Chrome browser.

**Comment by Simonwep** [comment]
Version? I cannot reproduce it with these little informations... At least the environment, style / script including or packaging tool would be helpful!

**Comment by JakeOcean** [comment]
I noticed this issue with firefox

**Comment by SkaveRat** [comment]
Tested with Chrome 69+ and firefox 61+

diff-ing the two versions, I'd guess it has something to do with the introduction of initializing via [`requestAnimationFrame`](https://github.com/Simonwep/pickr/blob/2226327ddc0c8e672e0ba51f1c8f3279cf5b5248/src/js/pickr.js#L79) .
If I had to guess, there is something (maybe in the dependencies people use?) that messes with requestanimationframe.

**Comment by JakeOcean** [comment]
@SkaveRat 

In my case I noticed that I had the default within the 'components' array, and once I moved it above it worked as expected.  I cant remember where I copied the original demo code from where the defautl was in the wrong place

**Comment by LeFrach** [comment]
Hello, 
Same problem here (Chrome)

![image](https://user-images.githubusercontent.com/25138916/52697900-b884d100-2f72-11e9-8b52-acc42ed249ab.png)

**Comment by Simonwep** [comment]
Okay, thank you all! I'll try to reproduce / fix it! :)

**Comment by Simonwep** [comment]
I think this is also related to #4 and #31. [This comment](https://github.com/Simonwep/pickr/issues/4#issuecomment-397292974) seems to solve this bug (maybe). I'm not sure in which environment this bug appears... Be sure to load pickr's css before all the javascript. Otherwise things like @LeFrach's screenshot happens. Moreover, don't use the `defer` attribute.

For example, try to add all of your css in the `head` element and place your JS at the very bottom of `body`.

**Comment by LeFrach** [comment]
In my case the problem is due to bootstrap's tab, to solve my problem I put the pickrTab active. 

![image](https://user-images.githubusercontent.com/25138916/52732931-bac24c00-2fc1-11e9-87e1-43918caee089.png)

**Comment by nickbrit** [comment]
I can replicate this issue on `Tab 2` https://jsfiddle.net/zbpn59cd/4/. 
http://g.recordit.co/L56GZQACV8.gif

Chrome 71/ MacOS

**Comment by nickbrit** [comment]
I think it's because  the picker is not visible and `this.wrapper.offsetHeight` is 0.
https://github.com/Simonwep/pickr/blob/0c5b5c180cfb79c3760883859445459c2a4d18b6/src/js/pickr.js#L236
It's why `background` will be `linear-gradient(to top, rgba(0, 0, 0, 1), transparent), linear-gradient(to left, hsla(NaN, 100%, 50%, 1), rgba(255, 255, 255, 1))`.

**Comment by SkaveRat** [comment]
can confirm. not being visible is the cause. In my case it's also not visible on page load.

Just checked, and the pallette works fine when it's visible on page load.

**Comment by sudheerm589** [comment]
Yes, by debugging I too find out that not visible is the problem

**Comment by Simonwep** [comment]
Thanks to @nickbrit, fixed! JSFiddle fork: https://jsfiddle.net/ew9zq0sg/ see f354a347c754b082daa9dc6933316a39cde2b336 😃

**Comment by LeFrach** [comment]
Yes problem solved for me, thank you !
