### ISSUE TITLE
How to keep picker color always show ?

### ISSUE THREAD

**Issue by kristoff2016** [Simonwep/pickr#6]
Hello Simonwep,
thanks for nice plugin!

I want to keep picker color always stay on the page without hide.
I  tired use pickr.show() but when I click outside on body it will be hide picker color 

thanks for your help!

**Comment by Simonwep** [comment]
Yeah, that's currently the behavior so the user can cancel the current selection. Currently it isn't possible to show it always, but it would be an useful option. I will add it today!

**Comment by Simonwep** [comment]
I've added it in 6cece9e45840caf7f604207ff79529d9dfd53ebf :)
You could, if you want, clone / download it, because I will add another feature until I draft version 0.1.0 (and publishing it to npm). Be aware that changes which are NOT yet in a release, are not documented in the README.

To use it, simply add `showAlways: true` to your configuration object. `pickr.hide()` and `pickr.show()` will still work, except what you mentioned.

**Comment by kristoff2016** [comment]
Thank you so much for your help. I love it
