### ISSUE TITLE
Feature request : Click to save

### ISSUE THREAD

**Issue by Nuranto** [Simonwep/pickr#8]
For some simple cases, just clicking on the color (or to be more precise, mouseup) to save it is better.

**Comment by Simonwep** [comment]
What _color_ do you mean? You cannot archive this if the user wants to select a different hue value or opacity.

**Comment by Nuranto** [comment]
I mean: 
1/ you click to open Pickr
2/ you click down on the color palette
3/ you move your mouse to your colour
4/ you release your click (mouseup) => close Pickr & trigger onSave on the color of the mouse position of the mouseup event

But you're right, the case I explain is for a very simple/quick color picker

**Comment by Simonwep** [comment]
Ah, I know what you mean. You're right, in both cases :)
I close this issue because, in my case, this functionality cannot be accomplished.

But if you still want something like that, you can use the `onChange()` method in combination with 
```
pickr._saveColor(); // Saves the current color (not documented and official)
pickr.hide();       // Closes the pickr
```
to get to the same result.

It's a little bit hacky, but if you want, you can do it. But be aware that `_saveColor()` is _(not yet)_ official.
Maybe I could implement something like `forceSave()` to accomplish this (official). If you would find it useful, say it ;)

**Comment by Nuranto** [comment]
Thanks, that solution seems OK to me :D
Imho, if you want to make it official, the best is probably to add a bool option "saveOnMouseUp". When true, it would remove the save button, and automatically call 
`pickr._saveColor(); // Saves the current color (not documented and official)
pickr.hide();`
on change.
